spring:
  application:
    name:tinkoff-hw-5
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:misc}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true

application:
  categories-url: https://kudago.com/public-api/v1.4/place-categories
  locations-url: https://kudago.com/public-api/v1.4/locations
