-- liquibase formatted sql

-- changeset oj:1

CREATE TABLE IF NOT EXISTS category (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);
